from typing import Any

class CryptContext:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def verify(self, secret: str, hash: str) -> bool: ...
    def hash(self, secret: str) -> str: ...
