from typing import Any

class String:
    def __init__(self, length: int | None = ...) -> None: ...

class Boolean:
    def __init__(self) -> None: ...

class Text:
    def __init__(self) -> None: ...

class ForeignKey:
    def __init__(self, target: str, *args: Any, **kwargs: Any) -> None: ...

def select(*entities: Any, **kwargs: Any) -> Any: ...
