name: Deploy

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_SERVICE_NAME: ${{ secrets.GCP_SERVICE_NAME }}
  GAR_REPOSITORY: backend
  IMAGE_TAG: ${{ github.sha }}

concurrency:
  group: cloud-run-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud --quiet auth configure-docker "${GCP_REGION}-docker.pkg.dev"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute image URI
        run: |
          IMAGE_URI="${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT}/${GAR_REPOSITORY}/${GCP_SERVICE_NAME}:${IMAGE_TAG}"
          echo "IMAGE_URI=${IMAGE_URI}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_URI }}
          provenance: false

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${GCP_SERVICE_NAME}" \
            --image "${IMAGE_URI}" \
            --region "${GCP_REGION}" \
            --project "${GCP_PROJECT}" \
            --platform managed \
            --quiet
